package class

const (
	Container                   Class = "bg-white p-8 rounded-lg w-96"
	ContainerShadow             Class = "bg-white p-8 rounded-lg shadow-lg w-96"
	ContainerShadowHover        Class = "bg-white p-8 rounded-lg shadow-lg w-96 hover:shadow-2xl"
	ContainerShadowFocus        Class = "bg-white p-8 rounded-lg shadow-lg w-96 focus:shadow-2xl"
	ContainerShadowNone         Class = "bg-white p-8 rounded-lg shadow-none w-96"
	ContainerShadowMd           Class = "bg-white p-8 rounded-lg shadow-md w-96"
	ContainerShadowLg           Class = "bg-white p-8 rounded-lg shadow-lg w-96"
	ContainerShadowXl           Class = "bg-white p-8 rounded-lg shadow-xl w-96"
	ContainerShadow2Xl          Class = "bg-white p-8 rounded-lg shadow-2xl w-96"
	ContainerShadow3Xl          Class = "bg-white p-8 rounded-lg shadow-3xl w-96"
	ContainerShadowInner        Class = "bg-white p-8 rounded-lg shadow-inner w-96"
	ContainerShadowOutline      Class = "bg-white p-8 rounded-lg shadow-outline w-96"
	ContainerShadowNoneHover    Class = "bg-white p-8 rounded-lg shadow-none w-96 hover:shadow-none"
	ContainerShadowNoneFocus    Class = "bg-white p-8 rounded-lg shadow-none w-96 focus:shadow-none"
	ContainerShadowNoneActive   Class = "bg-white p-8 rounded-lg shadow-none w-96 active:shadow-none"
	ContainerShadowNoneDisabled Class = "bg-white p-8 rounded-lg shadow-none w-96 disabled:shadow-none"
	ContainerShadowNoneVisited  Class = "bg-white p-8 rounded-lg shadow-none w-96 visited:shadow-none"
	ContainerShadowNoneChecked  Class = "bg-white p-8 rounded-lg shadow-none w-96 checked:shadow-none"

	ContainerRoundedNone         Class = "bg-white p-8 rounded-none shadow-lg w-96"
	ContainerRoundedSm           Class = "bg-white p-8 rounded-sm shadow-lg w-96"
	ContainerRoundedMd           Class = "bg-white p-8 rounded-md shadow-lg w-96"
	ContainerRoundedLg           Class = "bg-white p-8 rounded-lg shadow-lg w-96"
	ContainerRoundedXl           Class = "bg-white p-8 rounded-xl shadow-lg w-96"
	ContainerRounded2Xl          Class = "bg-white p-8 rounded-2xl shadow-lg w-96"
	ContainerRounded3Xl          Class = "bg-white p-8 rounded-3xl shadow-lg w-96"
	ContainerRoundedNoneHover    Class = "bg-white p-8 rounded-none shadow-lg w-96 hover:rounded-lg"
	ContainerRoundedNoneFocus    Class = "bg-white p-8 rounded-none shadow-lg w-96 focus:rounded-lg"
	ContainerRoundedNoneActive   Class = "bg-white p-8 rounded-none shadow-lg w-96 active:rounded-lg"
	ContainerRoundedNoneDisabled Class = "bg-white p-8 rounded-none shadow-lg w-96 disabled:rounded-lg"
	ContainerRoundedNoneVisited  Class = "bg-white p-8 rounded-none shadow-lg w-96 visited:rounded-lg"
	ContainerRoundedNoneChecked  Class = "bg-white p-8 rounded-none shadow-lg w-96 checked:rounded-lg"

	ContainerRoundedSmHover    Class = "bg-white p-8 rounded-sm shadow-lg w-96 hover:rounded-lg"
	ContainerRoundedSmFocus    Class = "bg-white p-8 rounded-sm shadow-lg w-96 focus:rounded-lg"
	ContainerRoundedSmActive   Class = "bg-white p-8 rounded-sm shadow-lg w-96 active:rounded-lg"
	ContainerRoundedSmDisabled Class = "bg-white p-8 rounded-sm shadow-lg w-96 disabled:rounded-lg"
	ContainerRoundedSmVisited  Class = "bg-white p-8 rounded-sm shadow-lg w-96 visited:rounded-lg"
	ContainerRoundedSmChecked  Class = "bg-white p-8 rounded-sm shadow-lg w-96 checked:rounded-lg"

	ContainerRoundedMdHover    Class = "bg-white p-8 rounded-md shadow-lg w-96 hover:rounded-lg"
	ContainerRoundedMdFocus    Class = "bg-white p-8 rounded-md shadow-lg w-96 focus:rounded-lg"
	ContainerRoundedMdActive   Class = "bg-white p-8 rounded-md shadow-lg w-96 active:rounded-lg"
	ContainerRoundedMdDisabled Class = "bg-white p-8 rounded-md shadow-lg w-96 disabled:rounded-lg"
	ContainerRoundedMdVisited  Class = "bg-white p-8 rounded-md shadow-lg w-96 visited:rounded-lg"
	ContainerRoundedMdChecked  Class = "bg-white p-8 rounded-md shadow-lg w-96 checked:rounded-lg"

	ContainerRoundedLgHover    Class = "bg-white p-8 rounded-lg shadow-lg w-96 hover:rounded-lg"
	ContainerRoundedLgFocus    Class = "bg-white p-8 rounded-lg shadow-lg w-96 focus:rounded-lg"
	ContainerRoundedLgActive   Class = "bg-white p-8 rounded-lg shadow-lg w-96 active:rounded-lg"
	ContainerRoundedLgDisabled Class = "bg-white p-8 rounded-lg shadow-lg w-96 disabled:rounded-lg"
	ContainerRoundedLgVisited  Class = "bg-white p-8 rounded-lg shadow-lg w-96 visited:rounded-lg"
	ContainerRoundedLgChecked  Class = "bg-white p-8 rounded-lg shadow-lg w-96 checked:rounded-lg"

	ContainerRoundedXlHover    Class = "bg-white p-8 rounded-xl shadow-lg w-96 hover:rounded-lg"
	ContainerRoundedXlFocus    Class = "bg-white p-8 rounded-xl shadow-lg w-96 focus:rounded-lg"
	ContainerRoundedXlActive   Class = "bg-white p-8 rounded-xl shadow-lg w-96 active:rounded-lg"
	ContainerRoundedXlDisabled Class = "bg-white p-8 rounded-xl shadow-lg w-96 disabled:rounded-lg"
	ContainerRoundedXlVisited  Class = "bg-white p-8 rounded-xl shadow-lg w-96 visited:rounded-lg"
	ContainerRoundedXlChecked  Class = "bg-white p-8 rounded-xl shadow-lg w-96 checked:rounded-lg"

	ContainerRounded2XlHover    Class = "bg-white p-8 rounded-2xl shadow-lg w-96 hover:rounded-lg"
	ContainerRounded2XlFocus    Class = "bg-white p-8 rounded-2xl shadow-lg w-96 focus:rounded-lg"
	ContainerRounded2XlActive   Class = "bg-white p-8 rounded-2xl shadow-lg w-96 active:rounded-lg"
	ContainerRounded2XlDisabled Class = "bg-white p-8 rounded-2xl shadow-lg w-96 disabled:rounded-lg"
	ContainerRounded2XlVisited  Class = "bg-white p-8 rounded-2xl shadow-lg w-96 visited:rounded-lg"
	ContainerRounded2XlChecked  Class = "bg-white p-8 rounded-2xl shadow-lg w-96 checked:rounded-lg"

	ContainerRounded3XlHover    Class = "bg-white p-8 rounded-3xl shadow-lg w-96 hover:rounded-lg"
	ContainerRounded3XlFocus    Class = "bg-white p-8 rounded-3xl shadow-lg w-96 focus:rounded-lg"
	ContainerRounded3XlActive   Class = "bg-white p-8 rounded-3xl shadow-lg w-96 active:rounded-lg"
	ContainerRounded3XlDisabled Class = "bg-white p-8 rounded-3xl shadow-lg w-96 disabled:rounded-lg"
	ContainerRounded3XlVisited  Class = "bg-white p-8 rounded-3xl shadow-lg w-96 visited:rounded-lg"
	ContainerRounded3XlChecked  Class = "bg-white p-8 rounded-3xl shadow-lg w-96 checked:rounded-lg"
)
